### ISSUE TITLE
where to set MIMALLOC_RESERVE_HUGE_OS_PAGES

### ISSUE THREAD

**Issue by bin22004** [KeinNiemand/LargePageInjectorMods#10]
Ok my question may be a bit stupid but could you tell me where to set this thing, thanks a lot

**Comment by KeinNiemand** [comment]
Search for environment in the windows search bar, open the thing that says something about user environment variables, when you open that you should have your user envoirment variables at the top and you should be able to add an enviourment varibale by clicking add and adding MIMALLOC_RESERVE_HUGE_OS_PAGES with the value being however many gigabytes you want to allocate.
Or just google how to edit user user environment variables on windows.
