### ISSUE TITLE
LockPagesInMemory

### ISSUE THREAD

**Issue by Valoneu** [KeinNiemand/LargePageInjectorMods#3]
I tried everything but i cant seems to enable this. Im on windows 10 home.

**Comment by KeinNiemand** [comment]
Apprently you need Windows 10/11 Pro to enable it and while there is probably some way to bypass that I don't know how since I have I have Windows 10/11 Pro, so I can't really help you. I'm going to update the instructions in the readme to list Windows Pro as a requirement.

**Comment by Valoneu** [comment]
Okay, unlucky, ill try to bypass it somehow one more time. Thanks for the response.

**Comment by ThenTech** [comment]
@Valoneu As the Group Policy and Security Policy editors are only available in the Pro or Edu editions of Windows, you could try to enable the Group Policy Editor through other means, e.g. see [this](https://www.makeuseof.com/tag/access-group-policy-editor-even-windows-home-settings-try/) or [this](https://awesomeprojectsxyz.blogspot.com/2017/11/windows-10-home-how-to-enable-lock.html).

When in the Group Policy Editor, go to `Computer Configuration\Windows Settings\Security Settings\Local Policies\User Rights Assignment` and find the `LockPagesInMemory` key as per the README.

**Comment by Valoneu** [comment]
i did but it clashes with smthing cause it just doesent get enabled, i have pro version rn so ill try it with that

**Comment by Valoneu** [comment]
nope it still doesent get enabled my windows is just fcked i guess
